// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration - you'll need to add a web app in Firebase Console to get these values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq_dY7T_pnbNDGhvhqaDs9sxcw0zz1CyE',
    appId: '1:1001807286020:web:YOUR_WEB_APP_ID', // You need to add web app in Firebase Console
    messagingSenderId: '1001807286020',
    projectId: 'massagebookingapp-5a234',
    authDomain: 'massagebookingapp-5a234.firebaseapp.com',
    storageBucket: 'massagebookingapp-5a234.firebasestorage.app',
  );

  // Android configuration from google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq_dY7T_pnbNDGhvhqaDs9sxcw0zz1CyE',
    appId: '1:1001807286020:android:ad7b7bff359022baca8a51',
    messagingSenderId: '1001807286020',
    projectId: 'massagebookingapp-5a234',
    storageBucket: 'massagebookingapp-5a234.firebasestorage.app',
  );

  // iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq_dY7T_pnbNDGhvhqaDs9sxcw0zz1CyE',
    appId: '1:1001807286020:ios:YOUR_IOS_APP_ID', // You need to add iOS app in Firebase Console
    messagingSenderId: '1001807286020',
    projectId: 'massagebookingapp-5a234',
    storageBucket: 'massagebookingapp-5a234.firebasestorage.app',
    iosBundleId: 'com.carlo.therapy',
  );
}
